name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    uses: KeibaAI-developer/library-workflow/.github/workflows/ci.yml@main
    with:
      package_name: race_data
      repo_name: race-data
      dependency_library: 'keiba-data-interface keiba-domain@develop'
